main: dk.muj.derius.DeriusSmithing
name: Derius-Smithing
version: 0.1_dev
#website: http://muj.dk/Derius
authors: [madus, ulumulu1510]
description: §eThis is the smithing skill for the Derius framework
depend: [DeriusCore]
load: startup
